create table public.player_counts (
  id bigint generated by default as identity not null,
  timestamp timestamp with time zone not null,
  player_count integer not null,
  server_id text not null,
  created_at timestamp with time zone null default now(),
  constraint player_counts_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists player_counts_server_id_idx on public.player_counts using btree (server_id) TABLESPACE pg_default;

create table public.server_xref (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  server_id text null,
  server_name text null,
  "order" integer null,
  constraint server_xref_pkey primary key (id)
) TABLESPACE pg_default;