-- =====================================================
-- Alert Subscriptions Schema
-- =====================================================
-- Purpose: Store user-defined alert rules evaluated by the alert engine
--          (evaluateAlertSubscriptions) on each cron tick.
--          - R3.1: 'player_count_below' rules alert when a server's player
--                  count drops below a user-chosen threshold.
--          - R3.2: 'streamer_live' rules alert when a tracked streamer goes
--                  live on Twitch or Kick.
--          - R3.7: edge-triggered delivery is driven by last_condition_state
--                  ('cleared' -> 'met' transitions fire once, not repeatedly).
--          - R9.4: every row is owned by exactly one App_User (user_id).
--
-- Access:  Owner-only access (R9.4) is enforced in the `lib/` data-access layer
--          (the owner-scoped accessor); the server-side alert engine reads all
--          enabled rules via the service-role client.
--
-- Migration: Defined in client-agnostic terms (explicit columns, types, checks,
--          and indexes) so it remains expressible in both the current schema
--          and a Prisma schema during the in-flight RDS migration (R9.2).
-- =====================================================

-- Create the alert_subscriptions table
create table if not exists public.alert_subscriptions (
  id bigint generated by default as identity not null,
  user_id bigint not null references public.app_users(id) on delete cascade,
  type text not null constraint alert_subscriptions_type_check
    check (type in ('player_count_below', 'streamer_live')),
  server_id text null,
  threshold integer null,
  streamer_username text null,
  streamer_platform text null constraint alert_subscriptions_streamer_platform_check
    check (streamer_platform in ('twitch', 'kick')),
  is_enabled boolean not null default true,
  last_condition_state text not null default 'cleared'
    constraint alert_subscriptions_last_condition_state_check
    check (last_condition_state in ('met', 'cleared')),
  last_triggered_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint alert_subscriptions_pkey primary key (id)
);

-- Index for fetching a user's subscriptions (owner-scoped reads, R3.8)
create index if not exists idx_alert_subscriptions_user
  on public.alert_subscriptions using btree (user_id);

-- Index for the alert engine scanning enabled rules by type (R3.1/R3.2)
create index if not exists idx_alert_subscriptions_type_enabled
  on public.alert_subscriptions using btree (type, is_enabled);

-- Partial index for player-count rules keyed by server (R3.1 evaluation)
create index if not exists idx_alert_subscriptions_server
  on public.alert_subscriptions using btree (server_id)
  where type = 'player_count_below';

-- Partial index for streamer-live rules keyed by streamer/platform (R3.2)
create index if not exists idx_alert_subscriptions_streamer
  on public.alert_subscriptions using btree (streamer_username, streamer_platform)
  where type = 'streamer_live';

-- =====================================================
-- Documentation
-- =====================================================
comment on table public.alert_subscriptions is 'User-defined alert rules evaluated by the alert engine (R3). Owner-scoped in the lib layer (R9.4).';
comment on column public.alert_subscriptions.id is 'Primary key, auto-incrementing';
comment on column public.alert_subscriptions.user_id is 'Owning App_User (R9.4); cascades on user deletion';
comment on column public.alert_subscriptions.type is 'Rule type: player_count_below (R3.1) or streamer_live (R3.2)';
comment on column public.alert_subscriptions.server_id is 'Target FiveM server id for player_count_below rules';
comment on column public.alert_subscriptions.threshold is 'Player-count threshold for player_count_below rules (R3.1)';
comment on column public.alert_subscriptions.streamer_username is 'Tracked streamer username for streamer_live rules (R3.2)';
comment on column public.alert_subscriptions.streamer_platform is 'Streamer platform for streamer_live rules: twitch or kick';
comment on column public.alert_subscriptions.is_enabled is 'Whether the rule is actively evaluated';
comment on column public.alert_subscriptions.last_condition_state is 'Edge-trigger state: cleared or met; cleared->met fires once (R3.7)';
comment on column public.alert_subscriptions.last_triggered_at is 'Time the rule last fired a notification';
