-- Alert history table for tracking all monitoring alerts
-- Stores alerts sent via Discord webhook and displayed in admin panel

CREATE TABLE IF NOT EXISTS public.alert_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  -- Alert details
  alert_type TEXT NOT NULL CHECK (alert_type IN (
    'data_gap', 'api_failure', 'all_servers_down', 'server_down',
    'anomaly_spike', 'anomaly_drop', 'collection_stale', 'database_error'
  )),
  severity TEXT NOT NULL DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'critical')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  
  -- Context
  server_id TEXT NULL,
  details JSONB NULL,
  
  -- Resolution tracking
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  resolved_at TIMESTAMP WITH TIME ZONE NULL,
  
  -- Notification delivery
  discord_sent BOOLEAN NOT NULL DEFAULT FALSE,
  discord_sent_at TIMESTAMP WITH TIME ZONE NULL,
  
  CONSTRAINT alert_history_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS alert_history_created_idx ON public.alert_history (created_at DESC);
CREATE INDEX IF NOT EXISTS alert_history_type_idx ON public.alert_history (alert_type, severity);
CREATE INDEX IF NOT EXISTS alert_history_unresolved_idx ON public.alert_history (resolved, created_at DESC) WHERE resolved = FALSE;

-- System settings for monitoring config (uses existing system_settings table if available)
-- If system_settings doesn't exist, the app will use env vars as fallback
