-- =====================================================
-- Anomaly Records Schema
-- =====================================================
-- Purpose: Persist player-count anomalies flagged by the Anomaly_Detector so
--          they can be monitored by admins and (optionally) surfaced publicly.
--          - R7.2: record anomalous DROPS with the server id, observation
--                  timestamp, observed value, expected value, and direction.
--          - R7.3: record anomalous SPIKES with the same fields.
--          - R7.4: rows feed the admin monitoring view
--                  (`app/admin/monitoring/page.tsx`).
--          - R7.5: rows are surfaced on a server's public-facing pages WHEN
--                  public anomaly surfacing is enabled.
--          - R7.6: `is_active` marks an anomaly as live so a duplicate for the
--                  same (server_id, direction) within the configured window can
--                  be suppressed instead of inserting a new record.
--          Reuses the existing `lib/monitoring.ts` percent-deviation + minimum
--          absolute-change approach but persists observed/expected/direction to
--          this dedicated table.
--
-- Access:  Writes come from the server-side Anomaly_Detector cron (via the
--          service-role client). Admin monitoring reads all anomalies (R7.4);
--          public surfacing (R7.5) is gated by the `anomaly_public` feature
--          flag in the application layer.
--
-- Migration: Defined in client-agnostic terms (explicit columns, types, and
--          indexes) so it stays expressible in both the current schema and a
--          Prisma schema during the in-flight RDS migration (R9.2).
-- =====================================================

-- Create the anomaly_records table
create table if not exists public.anomaly_records (
  id bigint generated by default as identity not null,
  server_id text not null,
  timestamp timestamp with time zone not null,
  observed_value integer not null,
  expected_value integer not null,
  direction text not null,
  deviation_percent integer not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint anomaly_records_pkey primary key (id),
  constraint anomaly_records_direction_check check (direction in ('spike', 'drop'))
);

-- Composite index for fetching a server's recent anomalies by direction (R7.4 reads)
create index if not exists idx_anomaly_records_server_direction_created
  on public.anomaly_records using btree (server_id, direction, created_at desc);

-- Index for time-ordered scans across all servers (admin monitoring feed)
create index if not exists idx_anomaly_records_created
  on public.anomaly_records using btree (created_at desc);

-- Partial index for the dedup window lookup of active anomalies per server (R7.6)
create index if not exists idx_anomaly_records_server_active
  on public.anomaly_records using btree (server_id, is_active)
  where is_active = true;

-- =====================================================
-- Documentation
-- =====================================================
comment on table public.anomaly_records is 'Persisted player-count anomalies for admin monitoring (R7.4) and flag-gated public surfacing (R7.5). Dedup via is_active within a window (R7.6).';
comment on column public.anomaly_records.id is 'Primary key, auto-incrementing';
comment on column public.anomaly_records.server_id is 'FiveM server identifier the anomaly applies to (R7.2/R7.3)';
comment on column public.anomaly_records.timestamp is 'Observation time of the anomalous data point (R7.2/R7.3)';
comment on column public.anomaly_records.observed_value is 'Observed player count at the anomalous data point (R7.2/R7.3)';
comment on column public.anomaly_records.expected_value is 'Expected player count for that time (R7.2/R7.3)';
comment on column public.anomaly_records.direction is 'Anomaly direction: spike or drop (R7.2/R7.3)';
comment on column public.anomaly_records.deviation_percent is 'Percent deviation of observed from expected value';
comment on column public.anomaly_records.is_active is 'Whether the anomaly is still active; used for dedup within the configured window (R7.6)';
comment on column public.anomaly_records.created_at is 'Time the anomaly record was created';
