-- Comparison Preferences Table
-- Stores the per-user pinned-server set for the Server Comparison View (R2).
-- Each authenticated App_User has at most one preferences row holding the
-- 2-4 servers they have pinned plus their last-selected time range.
--
-- Migration-safe / client-agnostic (R9.2): this definition uses only column
-- types, indexes, and an owner foreign key that are expressible in BOTH the
-- current schema and a Prisma schema, mirroring the existing `user_favorites`
-- convention. Owner-only access (R9.4) is enforced in the `lib/` data-access
-- layer (the owner-scoped accessor), so the guarantee survives the migration.
create table if not exists public.comparison_preferences (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  pinned_server_ids text[] not null default '{}', -- 2-4 server ids, validated in lib (R2.2/R2.3)
  time_range text, -- last selected time range; nullable, validated/defaulted in lib
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- One preferences row per user. This unique index also satisfies the
-- index(user_id) lookup requirement, so a separate plain index would be
-- redundant.
create unique index if not exists idx_comparison_prefs_user_unique on public.comparison_preferences(user_id);
