-- App Users Table
-- Stores regular (non-admin) user profiles
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade unique,
  discord_id text unique,
  username text,
  avatar_url text,
  created_at timestamp with time zone default current_timestamp,
  last_login_at timestamp with time zone,
  constraint app_users_username_format check (char_length(username) > 0 and char_length(username) <= 64)
);

-- Indexes for efficient queries
create index if not exists idx_app_users_auth_id on public.app_users(auth_user_id);
create index if not exists idx_app_users_discord_id on public.app_users(discord_id);
create index if not exists idx_app_users_username on public.app_users(username);

-- Row-level security
alter table public.app_users enable row level security;

-- RLS Policy: Users can only see their own profile
create policy "Users can view own profile"
  on app_users for select
  using (auth.uid() = auth_user_id);

-- RLS Policy: Users can insert their own profile
create policy "Users can insert own profile"
  on app_users for insert
  with check (auth.uid() = auth_user_id);

-- RLS Policy: Users can only update their own profile
create policy "Users can update own profile"
  on app_users for update
  using (auth.uid() = auth_user_id);
