-- Twitch Clips Table
-- Stores aggregated clips from streamers who have played on servers
-- Accumulates over time (no deletion), only marks as invalid

create table if not exists public.twitch_clips (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  clip_id text not null unique,
  streamer_username text not null,
  clip_title text not null,
  view_count integer not null default 0,
  duration_seconds numeric not null,
  thumbnail_url text not null,
  embed_url text not null,
  "serverId" text not null,
  is_valid boolean not null default true,
  twitch_created_at timestamp with time zone not null,
  last_validated_at timestamp with time zone null,
  constraint twitch_clips_pkey primary key (id)
) TABLESPACE pg_default;

-- Indexes for efficient querying
-- Primary query pattern: fetch clips for a server, optionally filtered by streamer
create index if not exists idx_clips_server on public.twitch_clips ("serverId");
create index if not exists idx_clips_streamer on public.twitch_clips (streamer_username);

-- Partial index: only valid clips (used in API queries)
create index if not exists idx_clips_valid on public.twitch_clips (is_valid) where is_valid = true;

-- Index for sorting by views
create index if not exists idx_clips_views on public.twitch_clips (view_count desc);

-- Composite index for common query pattern
create index if not exists idx_clips_server_valid_views on public.twitch_clips ("serverId", is_valid, view_count desc) where is_valid = true;

-- Enable RLS for security (follow existing pattern from other tables)
alter table public.twitch_clips enable row level security;
