-- Streamer Server History Table
-- Tracks which streamers have played on which servers
-- Used by clips ETL to determine which streamers to monitor for clips

create table if not exists public.streamer_server_history (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  "serverId" text not null,
  streamer_username text not null,
  platform text not null check (platform in ('twitch', 'kick')),
  first_seen timestamp with time zone not null default CURRENT_TIMESTAMP,
  last_seen timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint streamer_server_history_pkey primary key (id),
  constraint streamer_server_history_unique unique ("serverId", streamer_username, platform)
) TABLESPACE pg_default;

-- Indexes for efficient lookups
create index if not exists idx_streamer_history_server on public.streamer_server_history ("serverId");
create index if not exists idx_streamer_history_username on public.streamer_server_history (streamer_username);
create index if not exists idx_streamer_history_platform_server on public.streamer_server_history (platform, "serverId");

-- Enable RLS for security (follow existing pattern from other tables)
alter table public.streamer_server_history enable row level security;
