-- User Favorites Table
-- Stores clips users have saved with metadata
create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  clip_id text not null,
  platform text not null, -- 'twitch' or 'kick'
  saved_at timestamp with time zone default current_timestamp,
  notes text,
  categories text[], -- array of category tags
  viewing_history timestamp with time zone[], -- array of times user viewed
  unique(user_id, clip_id, platform)
);

-- Indexes for common queries
create index if not exists idx_favorites_user on public.user_favorites(user_id);
create index if not exists idx_favorites_user_platform on public.user_favorites(user_id, platform);
create index if not exists idx_favorites_user_saved_at on public.user_favorites(user_id, saved_at desc);
create index if not exists idx_favorites_clip_id on public.user_favorites(clip_id);

-- Row-level security
alter table public.user_favorites enable row level security;

-- RLS Policy: Users can only see their own favorites
create policy "Users can view own favorites"
  on user_favorites for select
  using (user_id = (select id from app_users where auth_user_id = auth.uid()));

-- RLS Policy: Users can only insert their own favorites
create policy "Users can insert own favorites"
  on user_favorites for insert
  with check (user_id = (select id from app_users where auth_user_id = auth.uid()));

-- RLS Policy: Users can only update their own favorites
create policy "Users can update own favorites"
  on user_favorites for update
  using (user_id = (select id from app_users where auth_user_id = auth.uid()));

-- RLS Policy: Users can only delete their own favorites
create policy "Users can delete own favorites"
  on user_favorites for delete
  using (user_id = (select id from app_users where auth_user_id = auth.uid()));
