-- api2db/sql/create_character_extractions.sql
-- Character extraction cache + review state for Streamer Character Tracking.
-- One row per distinct (streamer, title text). Accumulates over time.

create table if not exists public.character_extractions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone null default CURRENT_TIMESTAMP,
  streamer_name text not null,
  source_title text not null,
  -- Extractor output (R2.1, R2.7). character_name null => "no character found".
  character_name text null,
  confidence numeric(4, 3) not null check (confidence >= 0 and confidence <= 1),
  extraction_method text not null check (extraction_method in ('ai', 'fallback')),
  -- Review/resolution state (R6). Auto 'confirmed' when confidence >= threshold,
  -- else 'pending'. Admin actions set 'confirmed'/'overridden'/'rejected'.
  review_state text not null default 'pending'
    check (review_state in ('pending', 'confirmed', 'overridden', 'rejected')),
  override_name text null,                       -- admin correction (R6.4)
  reviewed_by text null,
  reviewed_at timestamp with time zone null,
  constraint character_extractions_pkey primary key (id)
)

-- Idempotency key: at most one extraction per (streamer, title), case-insensitive
-- on the streamer (R2.8, R9.3). Titles are short; safe to index directly.
create unique index if not exists uq_char_extractions_streamer_title
  on public.character_extractions (lower(streamer_name), source_title);

-- Primary lookup: all extractions for a streamer.
create index if not exists idx_char_extractions_streamer
  on public.character_extractions (lower(streamer_name));

-- Review queue scan: pending results ordered by confidence.
create index if not exists idx_char_extractions_review
  on public.character_extractions (review_state, confidence)
  where review_state = 'pending';


comment on table public.character_extractions is
  'Per-(streamer,title) character extraction cache + review state. RLS on, service-role reads only.';
