-- Kick Clips Table
-- Stores aggregated clips from Kick streamers who have played on servers
-- Accumulates over time (no deletion), only marks as invalid
-- Structure mirrors twitch_clips for consistency

create table if not exists public.kick_clips (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  clip_id text not null unique,
  streamer_username text not null,
  clip_title text not null,
  view_count integer not null default 0,
  duration_seconds numeric not null,
  thumbnail_url text not null,
  clip_url text not null,
  "serverId" text not null,
  is_valid boolean not null default true,
  kick_created_at timestamp with time zone not null,
  last_validated_at timestamp with time zone null,
  -- Kick-specific fields
  channel_slug text not null,
  category_name text null,
  constraint kick_clips_pkey primary key (id)
) TABLESPACE pg_default;

-- Indexes for efficient querying
-- Primary query pattern: fetch clips for a server, optionally filtered by streamer
create index if not exists idx_kick_clips_server on public.kick_clips ("serverId");
create index if not exists idx_kick_clips_streamer on public.kick_clips (streamer_username);
create index if not exists idx_kick_clips_channel on public.kick_clips (channel_slug);

-- Partial index: only valid clips (used in API queries)
create index if not exists idx_kick_clips_valid on public.kick_clips (is_valid) where is_valid = true;

-- Index for sorting by views
create index if not exists idx_kick_clips_views on public.kick_clips (view_count desc);

-- Composite index for common query pattern
create index if not exists idx_kick_clips_server_valid_views on public.kick_clips ("serverId", is_valid, view_count desc) where is_valid = true;

-- Enable RLS for security (follow existing pattern from other tables)
alter table public.kick_clips enable row level security;

-- Comment on table for documentation
comment on table public.kick_clips is 'Stores clips from Kick streamers who have played on GTA RP servers';
comment on column public.kick_clips.clip_id is 'Unique identifier from Kick API';
comment on column public.kick_clips.channel_slug is 'Kick channel slug (used for URL construction)';
comment on column public.kick_clips.clip_url is 'Direct URL to the clip on Kick';
