-- =====================================================
-- Insights Reports Schema
-- =====================================================
-- Purpose: Persist retained monthly "wrapped" recap reports generated from the
--          Player_Count_Series so they remain viewable and shareable over time.
--          - R5.1: one Insights_Report is generated per calendar month once
--                  that month completes (keyed by `month` = 'YYYY-MM').
--          - R5.2/R5.3: `metrics` (jsonb) holds the month's notable stats —
--                  peak-activity day, busiest server, and largest
--                  month-over-month growth — with per-metric availability so a
--                  metric with insufficient data is stored as
--                  `{ "available": false }` rather than a wrong value.
--          - R5.4: `share_slug` backs a public share link that renders the same
--                  stored report for any visitor who opens it.
--          - R5.6: reports are immutable once generated and retained, so every
--                  previously generated monthly report stays browsable.
--          Reports are computed in `lib/insights.ts` from existing
--          `getPlayerCounts` reads (R9.3) and persisted here keyed by month.
--
-- Access:  Reports are public and read-only to clients (open by slug R5.4,
--          browse the retained list R5.6). The server-side monthly generation
--          cron writes rows via the service-role client; reports are immutable
--          once generated (R5.6).
--
-- Migration: Defined in client-agnostic terms (explicit columns, types, and
--          indexes) so it stays expressible in both the current schema and a
--          Prisma schema during the in-flight RDS migration (R9.2).
-- =====================================================

-- Create the insights_reports table
create table if not exists public.insights_reports (
  id bigint generated by default as identity not null,
  month text not null,
  metrics jsonb not null,
  generated_at timestamp with time zone not null default now(),
  share_slug text not null,
  constraint insights_reports_pkey primary key (id),
  constraint insights_reports_month_key unique (month),
  constraint insights_reports_share_slug_key unique (share_slug)
);

-- The unique constraints on `month` (R5.1/R5.6) and `share_slug` (R5.4) each
-- create a backing index, so month-keyed lookups and share-slug resolution are
-- already covered. Add a time-ordered index for listing retained reports newest
-- first (R5.6 reports list).
create index if not exists idx_insights_reports_generated
  on public.insights_reports using btree (generated_at desc);

-- =====================================================
-- Documentation
-- =====================================================
comment on table public.insights_reports is 'Retained monthly wrapped/insights reports generated per calendar month (R5.1), immutable and retained (R5.6), publicly shareable by slug (R5.4).';
comment on column public.insights_reports.id is 'Primary key, auto-incrementing';
comment on column public.insights_reports.month is 'Calendar month the report covers in YYYY-MM form; unique per month (R5.1/R5.6)';
comment on column public.insights_reports.metrics is 'Report metrics as jsonb (peak-activity day, busiest server, largest MoM growth) with per-metric availability; unavailable metrics stored as { available: false } (R5.2/R5.3)';
comment on column public.insights_reports.generated_at is 'Time the report was generated';
comment on column public.insights_reports.share_slug is 'Opaque public share-link slug that resolves to this report for any visitor; unique (R5.4)';
