-- =====================================================
-- Notification Deliveries Schema
-- =====================================================
-- Purpose: Append-only delivery log recording every notification attempt made
--          by the alert delivery worker.
--          - R3.10: each row captures the originating alert subscription, the
--                   push subscription used (if any), the delivery timestamp,
--                   the outcome, and an optional detail payload, so delivery can
--                   be audited and de-duplicated.
--          This is a LOG table, not per-user data: it has no user_id and is
--          linked to subscriptions via foreign keys. Ownership is derived
--          through alert_subscriptions when needed.
--
-- Access:  The server-side delivery worker writes every row via the
--          service-role client; it is not user-facing.
--
-- Migration: Defined in client-agnostic terms (explicit columns, types, checks,
--          and indexes) so it remains expressible in both the current schema
--          and a Prisma schema during the in-flight RDS migration (R9.2).
-- =====================================================

-- Create the notification_deliveries table
create table if not exists public.notification_deliveries (
  id bigint generated by default as identity not null,
  subscription_id bigint not null
    references public.alert_subscriptions(id) on delete cascade,
  push_subscription_id bigint null
    references public.push_subscriptions(id) on delete set null,
  delivered_at timestamp with time zone not null default now(),
  outcome text not null constraint notification_deliveries_outcome_check
    check (outcome in ('delivered', 'failed', 'expired')),
  detail jsonb null,
  constraint notification_deliveries_pkey primary key (id)
);

-- Composite index for a subscription's recent delivery history (R3.10)
create index if not exists idx_notification_deliveries_subscription
  on public.notification_deliveries using btree (subscription_id, delivered_at desc);

-- Index for time-ordered scans across all deliveries (R3.10)
create index if not exists idx_notification_deliveries_delivered
  on public.notification_deliveries using btree (delivered_at desc);

-- =====================================================
-- Documentation
-- =====================================================
comment on table public.notification_deliveries is 'Append-only log of alert delivery attempts (R3.10). Not user-facing and has no user_id.';
comment on column public.notification_deliveries.id is 'Primary key, auto-incrementing';
comment on column public.notification_deliveries.subscription_id is 'Alert subscription that produced the notification (R3.10); cascades on deletion';
comment on column public.notification_deliveries.push_subscription_id is 'Push endpoint used for delivery, if any; null on delete';
comment on column public.notification_deliveries.delivered_at is 'Time the delivery attempt was made (R3.10)';
comment on column public.notification_deliveries.outcome is 'Delivery outcome: delivered, failed, or expired (R3.10)';
comment on column public.notification_deliveries.detail is 'Optional JSON payload with error/status detail for the attempt';
