-- =====================================================
-- Push Subscriptions Schema
-- =====================================================
-- Purpose: Store per-user browser web-push endpoints used to deliver alert
--          notifications via the Web Push protocol (VAPID).
--          - R3.4: each row holds a browser PushSubscription (endpoint plus the
--                  p256dh and auth keys) registered by an App_User.
--          - R3.9: is_active is set to false when the push service returns
--                  404/410 for an endpoint, so the delivery worker skips dead
--                  subscriptions thereafter.
--          - R9.4: every row is owned by exactly one App_User (user_id).
--
-- Access:  Owner-only access (R9.4) is enforced in the `lib/` data-access layer
--          (the owner-scoped accessor); the server-side delivery worker reads
--          every active subscription via the service-role client.
--
-- Migration: Defined in client-agnostic terms (explicit columns, types, and
--          indexes) so it remains expressible in both the current schema and a
--          Prisma schema during the in-flight RDS migration (R9.2).
-- =====================================================

-- Create the push_subscriptions table
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity not null,
  user_id bigint not null references public.app_users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  is_active boolean not null default true,
  user_agent text null,
  created_at timestamp with time zone not null default now(),
  last_used_at timestamp with time zone null,
  constraint push_subscriptions_pkey primary key (id),
  constraint push_subscriptions_endpoint_key unique (endpoint)
);

-- Index for fetching a user's push subscriptions (owner-scoped reads, R3.8)
create index if not exists idx_push_subscriptions_user
  on public.push_subscriptions using btree (user_id);

-- Partial index for the delivery worker scanning live endpoints (R3.9)
create index if not exists idx_push_subscriptions_active
  on public.push_subscriptions using btree (is_active)
  where is_active = true;

-- =====================================================
-- Documentation
-- =====================================================
comment on table public.push_subscriptions is 'Per-user browser web-push endpoints for alert delivery (R3.4/R3.9). Owner-scoped in the lib layer (R9.4).';
comment on column public.push_subscriptions.id is 'Primary key, auto-incrementing';
comment on column public.push_subscriptions.user_id is 'Owning App_User (R9.4); cascades on user deletion';
comment on column public.push_subscriptions.endpoint is 'Unique push service URL from the browser PushSubscription (R3.4)';
comment on column public.push_subscriptions.p256dh is 'Client public key (p256dh) from the PushSubscription';
comment on column public.push_subscriptions.auth is 'Client auth secret from the PushSubscription';
comment on column public.push_subscriptions.is_active is 'False when the push service returns 404/410; skipped by the worker (R3.9)';
comment on column public.push_subscriptions.user_agent is 'User agent of the browser that registered the subscription';
comment on column public.push_subscriptions.last_used_at is 'Time a delivery was last attempted/succeeded against this endpoint';
