-- =====================================================
-- Server Capacity Tracking Schema
-- =====================================================
-- Purpose: Track server max capacity over time to enable
--          capacity analysis and "% time at max" statistics
-- Related: Issue #58 - Max capacity feature
-- =====================================================

-- Create the server_capacity table
CREATE TABLE IF NOT EXISTS public.server_capacity (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  max_capacity integer NOT NULL,
  server_id text NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT server_capacity_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create index on server_id for efficient queries
CREATE INDEX IF NOT EXISTS server_capacity_server_id_idx 
  ON public.server_capacity USING btree (server_id) 
  TABLESPACE pg_default;

-- Create index on timestamp for time-range queries
CREATE INDEX IF NOT EXISTS server_capacity_timestamp_idx 
  ON public.server_capacity USING btree (timestamp DESC) 
  TABLESPACE pg_default;

-- Create composite index for optimal query performance
CREATE INDEX IF NOT EXISTS server_capacity_server_timestamp_idx 
  ON public.server_capacity USING btree (server_id, timestamp DESC) 
  TABLESPACE pg_default;

-- Add comments for documentation
COMMENT ON TABLE public.server_capacity IS 'Stores server maximum capacity over time for capacity analysis and statistics';
COMMENT ON COLUMN public.server_capacity.id IS 'Primary key, auto-incrementing';
COMMENT ON COLUMN public.server_capacity.timestamp IS 'Timestamp when the capacity was recorded';
COMMENT ON COLUMN public.server_capacity.max_capacity IS 'Maximum player capacity (slots) for the server at this time';
COMMENT ON COLUMN public.server_capacity.server_id IS 'FiveM server identifier';
COMMENT ON COLUMN public.server_capacity.created_at IS 'Timestamp when the record was inserted into the database';
