-- Site Updates Schema
-- This table stores manually created site updates for the "Recent Changes" tab
-- Includes support for markdown formatting and categorization

CREATE TABLE public.site_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  -- Content
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  content_markdown TEXT NULL, -- Markdown-formatted version for rich formatting
  
  -- Categorization
  type TEXT NOT NULL DEFAULT 'announcement' CHECK (type IN ('feature', 'improvement', 'bugfix', 'announcement')),
  priority INTEGER NOT NULL DEFAULT 1, -- Higher numbers = higher priority
  tags TEXT[] DEFAULT ARRAY[]::TEXT[], -- Array of tags for filtering
  
  -- Publishing
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  publish_date TIMESTAMP WITH TIME ZONE NULL,
  
  -- Metadata
  created_by TEXT NULL,
  view_count BIGINT DEFAULT 0,
  
  CONSTRAINT site_updates_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Indexes for performance
CREATE INDEX site_updates_published_idx ON public.site_updates (is_published, publish_date DESC) WHERE is_published = TRUE;
CREATE INDEX site_updates_type_idx ON public.site_updates (type);
CREATE INDEX site_updates_priority_idx ON public.site_updates (priority DESC);
CREATE INDEX site_updates_created_at_idx ON public.site_updates (created_at DESC);

-- Update trigger for updated_at timestamp
CREATE TRIGGER update_site_updates_updated_at 
    BEFORE UPDATE ON public.site_updates 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Roadmap Items Table
-- Stores planned, in-progress, and completed features with voting support
CREATE TABLE public.roadmap_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  -- Content
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  description_markdown TEXT NULL, -- Markdown-formatted version
  
  -- Status and Priority
  status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'completed', 'cancelled')),
  priority INTEGER NOT NULL DEFAULT 1, -- Higher numbers = higher priority
  category TEXT NULL, -- e.g., "Server Tracking", "Analytics", "UI/UX"
  
  -- Publishing and Display
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 0, -- For manual ordering
  
  -- Voting
  vote_count BIGINT DEFAULT 0,
  
  -- Metadata
  created_by TEXT NULL,
  
  CONSTRAINT roadmap_items_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Indexes for performance
CREATE INDEX roadmap_items_published_idx ON public.roadmap_items (is_published, status, priority DESC) WHERE is_published = TRUE;
CREATE INDEX roadmap_items_status_idx ON public.roadmap_items (status);
CREATE INDEX roadmap_items_category_idx ON public.roadmap_items (category);
CREATE INDEX roadmap_items_vote_count_idx ON public.roadmap_items (vote_count DESC);
CREATE INDEX roadmap_items_display_order_idx ON public.roadmap_items (display_order);

-- Update trigger for updated_at timestamp
CREATE TRIGGER update_roadmap_items_updated_at 
    BEFORE UPDATE ON public.roadmap_items 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Roadmap Votes Table
-- Tracks user votes on roadmap items to prevent duplicate voting
CREATE TABLE public.roadmap_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  roadmap_item_id BIGINT NOT NULL REFERENCES public.roadmap_items(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL, -- From localStorage or session (IP + user agent hash)
  voted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  CONSTRAINT roadmap_votes_pkey PRIMARY KEY (id),
  CONSTRAINT roadmap_votes_unique UNIQUE (roadmap_item_id, user_id)
) TABLESPACE pg_default;

-- Indexes for performance
CREATE INDEX roadmap_votes_item_idx ON public.roadmap_votes (roadmap_item_id);
CREATE INDEX roadmap_votes_user_idx ON public.roadmap_votes (user_id);
CREATE INDEX roadmap_votes_voted_at_idx ON public.roadmap_votes (voted_at DESC);

-- Update Categories Table (Optional)
-- Allows organizing updates and roadmap items by category
CREATE TABLE public.update_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  -- Category Info
  name TEXT NOT NULL UNIQUE,
  icon TEXT NULL, -- Icon name or emoji
  color TEXT NULL, -- Hex color code
  description TEXT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  
  CONSTRAINT update_categories_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Indexes for performance
CREATE INDEX update_categories_name_idx ON public.update_categories (name);
CREATE INDEX update_categories_display_order_idx ON public.update_categories (display_order);

-- Row Level Security (RLS)
ALTER TABLE public.site_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roadmap_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roadmap_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.update_categories ENABLE ROW LEVEL SECURITY;

-- RLS Policies for site_updates
-- Public can read published updates
CREATE POLICY "Allow public read published updates" ON public.site_updates
  FOR SELECT USING (
    is_published = TRUE 
    AND (publish_date IS NULL OR publish_date <= NOW())
  );

-- Admin can read all updates
CREATE POLICY "Allow admin read all updates" ON public.site_updates
  FOR SELECT USING (TRUE);

-- Admin can insert updates
CREATE POLICY "Allow admin insert updates" ON public.site_updates
  FOR INSERT WITH CHECK (TRUE);

-- Admin can update updates
CREATE POLICY "Allow admin update updates" ON public.site_updates
  FOR UPDATE USING (TRUE) WITH CHECK (TRUE);

-- Admin can delete updates
CREATE POLICY "Allow admin delete updates" ON public.site_updates
  FOR DELETE USING (TRUE);

-- RLS Policies for roadmap_items
-- Public can read published roadmap items
CREATE POLICY "Allow public read published roadmap" ON public.roadmap_items
  FOR SELECT USING (is_published = TRUE);

-- Admin can read all roadmap items
CREATE POLICY "Allow admin read all roadmap" ON public.roadmap_items
  FOR SELECT USING (TRUE);

-- Admin can insert roadmap items
CREATE POLICY "Allow admin insert roadmap" ON public.roadmap_items
  FOR INSERT WITH CHECK (TRUE);

-- Admin can update roadmap items
CREATE POLICY "Allow admin update roadmap" ON public.roadmap_items
  FOR UPDATE USING (TRUE) WITH CHECK (TRUE);

-- Admin can delete roadmap items
CREATE POLICY "Allow admin delete roadmap" ON public.roadmap_items
  FOR DELETE USING (TRUE);

-- RLS Policies for roadmap_votes
-- Public can read votes
CREATE POLICY "Allow public read votes" ON public.roadmap_votes
  FOR SELECT USING (TRUE);

-- Public can insert votes
CREATE POLICY "Allow public insert votes" ON public.roadmap_votes
  FOR INSERT WITH CHECK (TRUE);

-- Public can delete their own votes
CREATE POLICY "Allow public delete own votes" ON public.roadmap_votes
  FOR DELETE USING (TRUE);

-- Admin can delete any votes
CREATE POLICY "Allow admin delete votes" ON public.roadmap_votes
  FOR DELETE USING (TRUE);

-- RLS Policies for update_categories
-- Public can read categories
CREATE POLICY "Allow public read categories" ON public.update_categories
  FOR SELECT USING (TRUE);

-- Admin can manage categories
CREATE POLICY "Allow admin manage categories" ON public.update_categories
  FOR ALL USING (TRUE);

-- Sample Data for Testing
INSERT INTO public.update_categories (name, icon, color, description, display_order) VALUES
('Server Tracking', '📊', '#1e40af', 'Server monitoring and player count features', 1),
('Analytics', '📈', '#7c3aed', 'Data analysis and reporting features', 2),
('UI/UX', '🎨', '#d97706', 'User interface and experience improvements', 3),
('Performance', '⚡', '#059669', 'Speed and optimization improvements', 4),
('Security', '🔒', '#dc2626', 'Security and privacy enhancements', 5);

-- Sample Site Updates
INSERT INTO public.site_updates (title, content, type, priority, is_published, publish_date, created_by) VALUES
(
  'Welcome to Site Updates',
  'We have launched a new Site Updates feature to keep you informed about recent changes and upcoming features.',
  'announcement',
  5,
  TRUE,
  NOW(),
  'system'
),
(
  'New Roadmap Feature',
  'Check out our roadmap to see what features we are planning to build next. You can vote on features you want to see!',
  'feature',
  4,
  TRUE,
  NOW(),
  'system'
);

-- Sample Roadmap Items
INSERT INTO public.roadmap_items (title, description, status, priority, category, is_published, display_order, created_by) VALUES
(
  'Real-time Server Status',
  'Display live server status with instant updates when servers go online or offline.',
  'in_progress',
  9,
  'Server Tracking',
  TRUE,
  1,
  'system'
),
(
  'Advanced Analytics Dashboard',
  'Create a comprehensive analytics dashboard with detailed player statistics and trends.',
  'planned',
  8,
  'Analytics',
  TRUE,
  2,
  'system'
),
(
  'Dark Mode Theme',
  'Implement a complete dark mode theme for better user experience in low-light environments.',
  'planned',
  7,
  'UI/UX',
  TRUE,
  3,
  'system'
),
(
  'Performance Optimization',
  'Optimize database queries and API responses for faster page load times.',
  'planned',
  6,
  'Performance',
  TRUE,
  4,
  'system'
),
(
  'Two-Factor Authentication',
  'Add optional two-factor authentication for enhanced account security.',
  'planned',
  8,
  'Security',
  TRUE,
  5,
  'system'
);
