-- Live User Tracking System - Database Schema
-- Phase 1: Database & Auth Setup
-- Source: PRD §4.1 FR-6, FR-9; Blueprint §6.1

-- ============================================================================
-- visitor_sessions table - Core tracking table
-- ============================================================================
-- Stores active visitor sessions with human/bot classification
-- Source: PRD §8.2 SL-1 through SL-4

CREATE TABLE IF NOT EXISTS public.visitor_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  last_heartbeat TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_bot BOOLEAN NOT NULL DEFAULT false,
  user_agent TEXT,
  ip_hash TEXT,
  CONSTRAINT visitor_sessions_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- ============================================================================
-- Indexes for Performance Optimization
-- ============================================================================
-- Source: PRD §4.2 NFR-2, §5.5.1; Blueprint §6.1
-- Critical for fast queries when counting active visitors

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_last_heartbeat 
  ON public.visitor_sessions USING BTREE (last_heartbeat) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_is_active 
  ON public.visitor_sessions USING BTREE (is_active) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_is_bot 
  ON public.visitor_sessions USING BTREE (is_bot) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_created_at 
  ON public.visitor_sessions USING BTREE (created_at) 
  TABLESPACE pg_default;

-- Composite index for efficient count queries
CREATE INDEX IF NOT EXISTS idx_visitor_sessions_active_bot 
  ON public.visitor_sessions USING BTREE (is_active, is_bot) 
  TABLESPACE pg_default;

-- ============================================================================
-- admin_users table - Admin authentication
-- ============================================================================
-- Stores admin user mappings for Supabase Auth
-- Source: PRD §4.1 FR-9; Blueprint §6.1

CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  auth_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_admin_users_auth_user_id 
  ON public.admin_users USING BTREE (auth_user_id) 
  TABLESPACE pg_default;

-- ============================================================================
-- Row Level Security (RLS) Policies
-- ============================================================================
-- Source: PRD §4.2 NFR-4; Blueprint §2.3

-- Enable RLS on both tables
ALTER TABLE public.visitor_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Policy: Service role can bypass RLS (for API endpoints)
CREATE POLICY "Service role bypass" ON public.visitor_sessions
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Policy: Anyone can insert visitor_sessions (for session creation from API)
-- This allows public API calls to create sessions
CREATE POLICY "Anyone can insert visitor_sessions" ON public.visitor_sessions
  FOR INSERT
  WITH CHECK (true);

-- Policy: Admins can view visitor_sessions
CREATE POLICY "Admins can view visitor_sessions" ON public.visitor_sessions
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.auth_user_id = auth.uid()
    )
  );

-- Policy: Admins can update visitor_sessions (for heartbeat)
CREATE POLICY "Admins can update visitor_sessions" ON public.visitor_sessions
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.auth_user_id = auth.uid()
    )
  );

-- Policy: Admins can view admin_users
CREATE POLICY "Admins can view admin_users" ON public.admin_users
  FOR SELECT
  USING (auth.uid() = auth_user_id);

-- ============================================================================
-- Helper Views for Analytics
-- ============================================================================
-- Source: PRD §4.1 FR-2, FR-11

-- View for current active visitor counts
CREATE OR REPLACE VIEW public.visitor_count_summary AS
SELECT
  COUNT(*) FILTER (WHERE is_active AND NOT is_bot) as active_humans,
  COUNT(*) FILTER (WHERE is_active AND is_bot) as active_bots,
  COUNT(*) FILTER (WHERE is_active) as total_active,
  NOW() as last_updated
FROM public.visitor_sessions;

-- View for hourly visitor statistics
CREATE OR REPLACE VIEW public.visitor_hourly_stats AS
SELECT
  DATE_TRUNC('hour', created_at) as hour,
  COUNT(*) FILTER (WHERE NOT is_bot) as humans,
  COUNT(*) FILTER (WHERE is_bot) as bots,
  COUNT(*) as total
FROM public.visitor_sessions
WHERE created_at > NOW() - INTERVAL '24 hours'
GROUP BY DATE_TRUNC('hour', created_at)
ORDER BY hour DESC;

-- ============================================================================
-- Cleanup Function for Old Sessions
-- ============================================================================
-- Source: PRD §4.1 FR-7; Blueprint §8 Phase 4
-- Deletes sessions older than 7 days

CREATE OR REPLACE FUNCTION public.cleanup_old_visitor_sessions()
RETURNS TABLE(deleted_count INT) AS $$
DECLARE
  v_deleted_count INT;
BEGIN
  DELETE FROM public.visitor_sessions
  WHERE created_at < NOW() - INTERVAL '7 days';
  
  GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
  
  RETURN QUERY SELECT v_deleted_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Scheduled Job Setup (Optional - requires pg_cron extension)
-- ============================================================================
-- Uncomment if pg_cron is available in your Supabase instance
-- This runs cleanup daily at 2 AM UTC

-- SELECT cron.schedule('cleanup-old-visitor-sessions', '0 2 * * *', 'SELECT public.cleanup_old_visitor_sessions()');

-- ============================================================================
-- Grants for Service Role
-- ============================================================================
-- Allow service role to manage visitor sessions (for API endpoints)

GRANT SELECT, INSERT, UPDATE ON public.visitor_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.admin_users TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_old_visitor_sessions() TO service_role;
